In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import datetime as dt
import scipy.stats as sps 
%matplotlib inline

In [2]:
mydata = pd.read_csv("alldata_risk_table.csv")

In [3]:
mydata.shape

(833507, 107)

In [4]:
mydata['RANDOM']=np.random.ranf(len(mydata))

In [5]:
mydata.describe()

,fraud_label,fulladdress_0_count,fulladdress_1_count,fulladdress_3_count,fulladdress_7_count,fulladdress_14_count,fulladdress_30_count,homephone_0_count,homephone_1_count,homephone_3_count,...,Days_fulladdress_homephone,Days_namedob_homephone,Days_firstname_ssn,Days_lastname_ssn,Days_firstname_fulladdress,Days_lastname_address,new_zip,zip3,Day_of _Month,RANDOM
count,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,...,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.000000,833507.00000,833507.000000,833507.000000,8.335070e+05
mean,0.014405,1.012017,1.024596,1.032133,1.039661,1.048484,1.064834,1.071030,1.201540,1.449198,...,332.631508,333.866159,330.583864,330.588522,331.823778,331.593441,50063.77716,500.142256,15.702407,5.000568e-01
std,0.119155,0.286968,0.490477,0.549730,0.587901,0.612078,0.636508,0.361285,0.621104,0.858705,...,91.722276,89.738583,94.138185,94.133517,92.259692,92.536431,28907.66453,289.078071,8.796267,2.889577e-01
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.00000,0.000000,1.000000,3.508798e-08
25%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,24992.00000,249.000000,8.000000,2.497454e-01
50%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,50516.00000,505.000000,16.000000,4.998545e-01
75%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,74458.00000,744.000000,23.000000,7.507201e-01
max,1.000000,24.000000,30.000000,30.000000,30.000000,30.000000,30.000000,22.000000,29.000000,30.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,99999.00000,999.000000,31.000000,9.999986e-01

In [6]:
goods=mydata[mydata['fraud_label']==0]
goods.shape

(821500, 108)

In [7]:
bads=mydata[mydata['fraud_label']==1]
bads.shape

(12007, 108)

In [8]:
numgoods=len(goods)
numbads=len(bads)

In [9]:
KS = pd.DataFrame(np.zeros((mydata.shape[1],3)))
i=0
for column in mydata:
    print(i,column)
    KS.loc[i,0]=column
    i = i+1
KS

0 fraud_label
1 nameDOB
2 fulladdress
3 namedob
4 fulladdress_0_count
5 fulladdress_1_count
6 fulladdress_3_count
7 fulladdress_7_count
8 fulladdress_14_count
9 fulladdress_30_count
10 homephone_0_count
11 homephone_1_count
12 homephone_3_count
13 homephone_7_count
14 homephone_14_count
15 homephone_30_count
16 namedob_0_count
17 namedob_1_count
18 namedob_3_count
19 namedob_7_count
20 namedob_14_count
21 namedob_30_count
22 ssn_0_count
23 ssn_1_count
24 ssn_3_count
25 ssn_7_count
26 ssn_14_count
27 ssn_30_count
28 ssnfulladdress_0_count
29 ssnfulladdress_1_count
30 ssnfulladdress_3_count
31 ssnfulladdress_7_count
32 ssnfulladdress_14_count
33 ssnfulladdress_30_count
34 ssnhomephone_0_count
35 ssnhomephone_1_count
36 ssnhomephone_3_count
37 ssnhomephone_7_count
38 ssnhomephone_14_count
39 ssnhomephone_30_count
40 ssnnamedob_0_count
41 ssnnamedob_1_count
42 ssnnamedob_3_count
43 ssnnamedob_7_count
44 ssnnamedob_14_count
45 ssnnamedob_30_count
46 fulladdressnamedob_0_count
47 fulladdressnamedob_1_count
48 fulladdressnamedob_3_count
49 fulladdressnamedob_7_count
50 fulladdressnamedob_14_count
51 fulladdressnamedob_30_count
52 fulladdresshomephone_0_count
53 fulladdresshomephone_1_count
54 fulladdresshomephone_3_count
55 fulladdresshomephone_7_count
56 fulladdresshomephone_14_count
57 fulladdresshomephone_30_count
58 namedobhomephone_0_count
59 namedobhomephone_1_count
60 namedobhomephone_3_count
61 namedobhomephone_7_count
62 namedobhomephone_14_count
63 namedobhomephone_30_count
64 firstnamessn_0_count
65 firstnamessn_1_count
66 firstnamessn_3_count
67 firstnamessn_7_count
68 firstnamessn_14_count
69 firstnamessn_30_count
70 lastnamessn_0_count
71 lastnamessn_1_count
72 lastnamessn_3_count
73 lastnamessn_7_count
74 lastnamessn_14_count
75 lastnamessn_30_count
76 firstnamefulladdress_0_count
77 firstnamefulladdress_1_count
78 firstnamefulladdress_3_count
79 firstnamefulladdress_7_count
80 firstnamefulladdress_14_count
81 firstnamefulladdress_30_count
82 lastnamefulladdress_0_count
83 lastnamefulladdress_1_count
84 lastnamefulladdress_3_count
85 lastnamefulladdress_7_count
86 lastnamefulladdress_14_count
87 lastnamefulladdress_30_count
88 Days_ssn
89 Days_fulladdress
90 Days_namedob
91 Days_homephone
92 Days_ssn_fulladdress
93 Days_ssn_namedob
94 Days_ssn_homephone
95 Days_fulladdress_namedob
96 Days_fulladdress_homephone
97 Days_namedob_homephone
98 Days_firstname_ssn
99 Days_lastname_ssn
100 Days_firstname_fulladdress
101 Days_lastname_address
102 Day_of_Week
103 new_zip
104 zip3
105 Month_of_Year
106 Day_of _Month
107 RANDOM

                                 0    1    2
0                      fraud_label  0.0  0.0
1                          nameDOB  0.0  0.0
2                      fulladdress  0.0  0.0
3                          namedob  0.0  0.0
4              fulladdress_0_count  0.0  0.0
5              fulladdress_1_count  0.0  0.0
6              fulladdress_3_count  0.0  0.0
7              fulladdress_7_count  0.0  0.0
8             fulladdress_14_count  0.0  0.0
9             fulladdress_30_count  0.0  0.0
10               homephone_0_count  0.0  0.0
11               homephone_1_count  0.0  0.0
12               homephone_3_count  0.0  0.0
13               homephone_7_count  0.0  0.0
14              homephone_14_count  0.0  0.0
15              homephone_30_count  0.0  0.0
16                 namedob_0_count  0.0  0.0
17                 namedob_1_count  0.0  0.0
18                 namedob_3_count  0.0  0.0
19                 namedob_7_count  0.0  0.0
20                namedob_14_count  0.0  0.0
21                namedob_30_count  0.0  0.0
22                     ssn_0_count  0.0  0.0
23                     ssn_1_count  0.0  0.0
24                     ssn_3_count  0.0  0.0
25                     ssn_7_count  0.0  0.0
26                    ssn_14_count  0.0  0.0
27                    ssn_30_count  0.0  0.0
28          ssnfulladdress_0_count  0.0  0.0
29          ssnfulladdress_1_count  0.0  0.0
..                             ...  ...  ...
78    firstnamefulladdress_3_count  0.0  0.0
79    firstnamefulladdress_7_count  0.0  0.0
80   firstnamefulladdress_14_count  0.0  0.0
81   firstnamefulladdress_30_count  0.0  0.0
82     lastnamefulladdress_0_count  0.0  0.0
83     lastnamefulladdress_1_count  0.0  0.0
84     lastnamefulladdress_3_count  0.0  0.0
85     lastnamefulladdress_7_count  0.0  0.0
86    lastnamefulladdress_14_count  0.0  0.0
87    lastnamefulladdress_30_count  0.0  0.0
88                        Days_ssn  0.0  0.0
89                Days_fulladdress  0.0  0.0
90                    Days_namedob  0.0  0.0
91                  Days_homephone  0.0  0.0
92            Days_ssn_fulladdress  0.0  0.0
93                Days_ssn_namedob  0.0  0.0
94              Days_ssn_homephone  0.0  0.0
95        Days_fulladdress_namedob  0.0  0.0
96      Days_fulladdress_homephone  0.0  0.0
97          Days_namedob_homephone  0.0  0.0
98              Days_firstname_ssn  0.0  0.0
99               Days_lastname_ssn  0.0  0.0
100     Days_firstname_fulladdress  0.0  0.0
101          Days_lastname_address  0.0  0.0
102                    Day_of_Week  0.0  0.0
103                        new_zip  0.0  0.0
104                           zip3  0.0  0.0
105                  Month_of_Year  0.0  0.0
106                  Day_of _Month  0.0  0.0
107                         RANDOM  0.0  0.0

[108 rows x 3 columns]

In [10]:
KS.columns=['field','ks','FDR']
KS

                             field   ks  FDR
0                      fraud_label  0.0  0.0
1                          nameDOB  0.0  0.0
2                      fulladdress  0.0  0.0
3                          namedob  0.0  0.0
4              fulladdress_0_count  0.0  0.0
5              fulladdress_1_count  0.0  0.0
6              fulladdress_3_count  0.0  0.0
7              fulladdress_7_count  0.0  0.0
8             fulladdress_14_count  0.0  0.0
9             fulladdress_30_count  0.0  0.0
10               homephone_0_count  0.0  0.0
11               homephone_1_count  0.0  0.0
12               homephone_3_count  0.0  0.0
13               homephone_7_count  0.0  0.0
14              homephone_14_count  0.0  0.0
15              homephone_30_count  0.0  0.0
16                 namedob_0_count  0.0  0.0
17                 namedob_1_count  0.0  0.0
18                 namedob_3_count  0.0  0.0
19                 namedob_7_count  0.0  0.0
20                namedob_14_count  0.0  0.0
21                namedob_30_count  0.0  0.0
22                     ssn_0_count  0.0  0.0
23                     ssn_1_count  0.0  0.0
24                     ssn_3_count  0.0  0.0
25                     ssn_7_count  0.0  0.0
26                    ssn_14_count  0.0  0.0
27                    ssn_30_count  0.0  0.0
28          ssnfulladdress_0_count  0.0  0.0
29          ssnfulladdress_1_count  0.0  0.0
..                             ...  ...  ...
78    firstnamefulladdress_3_count  0.0  0.0
79    firstnamefulladdress_7_count  0.0  0.0
80   firstnamefulladdress_14_count  0.0  0.0
81   firstnamefulladdress_30_count  0.0  0.0
82     lastnamefulladdress_0_count  0.0  0.0
83     lastnamefulladdress_1_count  0.0  0.0
84     lastnamefulladdress_3_count  0.0  0.0
85     lastnamefulladdress_7_count  0.0  0.0
86    lastnamefulladdress_14_count  0.0  0.0
87    lastnamefulladdress_30_count  0.0  0.0
88                        Days_ssn  0.0  0.0
89                Days_fulladdress  0.0  0.0
90                    Days_namedob  0.0  0.0
91                  Days_homephone  0.0  0.0
92            Days_ssn_fulladdress  0.0  0.0
93                Days_ssn_namedob  0.0  0.0
94              Days_ssn_homephone  0.0  0.0
95        Days_fulladdress_namedob  0.0  0.0
96      Days_fulladdress_homephone  0.0  0.0
97          Days_namedob_homephone  0.0  0.0
98              Days_firstname_ssn  0.0  0.0
99               Days_lastname_ssn  0.0  0.0
100     Days_firstname_fulladdress  0.0  0.0
101          Days_lastname_address  0.0  0.0
102                    Day_of_Week  0.0  0.0
103                        new_zip  0.0  0.0
104                           zip3  0.0  0.0
105                  Month_of_Year  0.0  0.0
106                  Day_of _Month  0.0  0.0
107                         RANDOM  0.0  0.0

[108 rows x 3 columns]

In [11]:
%%time
i=0
for column in mydata:
    KS['ks'][i]=sps.ks_2samp(goods[column],bads[column])[0]
    i = i+1

CPU times: user 55.3 s, sys: 1.35 s, total: 56.6 s
Wall time: 35.1 s

In [13]:
KS.sort_values(by='ks',ascending= False, inplace= True)
KS

                             field        ks  FDR
0                      fraud_label  1.000000  0.0
89                Days_fulladdress  0.328941  0.0
9             fulladdress_30_count  0.327827  0.0
8             fulladdress_14_count  0.317954  0.0
7              fulladdress_7_count  0.298436  0.0
6              fulladdress_3_count  0.276319  0.0
5              fulladdress_1_count  0.246519  0.0
88                        Days_ssn  0.224871  0.0
27                    ssn_30_count  0.224655  0.0
96      Days_fulladdress_homephone  0.224513  0.0
98              Days_firstname_ssn  0.224081  0.0
99               Days_lastname_ssn  0.223893  0.0
69           firstnamessn_30_count  0.223776  0.0
75            lastnamessn_30_count  0.223692  0.0
57   fulladdresshomephone_30_count  0.223523  0.0
90                    Days_namedob  0.223434  0.0
93                Days_ssn_namedob  0.223329  0.0
21                namedob_30_count  0.223080  0.0
45             ssnnamedob_30_count  0.222973  0.0
56   fulladdresshomephone_14_count  0.213874  0.0
26                    ssn_14_count  0.212569  0.0
68           firstnamessn_14_count  0.211992  0.0
20                namedob_14_count  0.211867  0.0
74            lastnamessn_14_count  0.211586  0.0
44             ssnnamedob_14_count  0.211206  0.0
55    fulladdresshomephone_7_count  0.195531  0.0
12               homephone_3_count  0.193148  0.0
19                 namedob_7_count  0.192239  0.0
25                     ssn_7_count  0.191997  0.0
13               homephone_7_count  0.191799  0.0
..                             ...       ...  ...
37            ssnhomephone_7_count  0.028493  0.0
61        namedobhomephone_7_count  0.028461  0.0
31          ssnfulladdress_7_count  0.028047  0.0
106                  Day_of _Month  0.018475  0.0
78    firstnamefulladdress_3_count  0.018215  0.0
84     lastnamefulladdress_3_count  0.015857  0.0
48      fulladdressnamedob_3_count  0.014836  0.0
30          ssnfulladdress_3_count  0.014434  0.0
60        namedobhomephone_3_count  0.014422  0.0
36            ssnhomephone_3_count  0.014322  0.0
1                          nameDOB  0.014123  0.0
3                          namedob  0.014123  0.0
103                        new_zip  0.013523  0.0
2                      fulladdress  0.013260  0.0
104                           zip3  0.013245  0.0
105                  Month_of_Year  0.012434  0.0
107                         RANDOM  0.011004  0.0
102                    Day_of_Week  0.009984  0.0
77    firstnamefulladdress_1_count  0.008507  0.0
83     lastnamefulladdress_1_count  0.006331  0.0
47      fulladdressnamedob_1_count  0.005444  0.0
59        namedobhomephone_1_count  0.005433  0.0
35            ssnhomephone_1_count  0.005427  0.0
29          ssnfulladdress_1_count  0.005364  0.0
76    firstnamefulladdress_0_count  0.003257  0.0
82     lastnamefulladdress_0_count  0.002086  0.0
46      fulladdressnamedob_0_count  0.001761  0.0
34            ssnhomephone_0_count  0.001703  0.0
58        namedobhomephone_0_count  0.001699  0.0
28          ssnfulladdress_0_count  0.001685  0.0

[108 rows x 3 columns]

In [14]:
%%time
topRows=int(round(len(mydata)*0.03))
j=0
for column in mydata:
    temp1=mydata.sort_values(column,ascending=False).head(topRows)
    temp2=mydata.sort_values(column,ascending=True).head(topRows)
    needed1=temp1.loc[:,'fraud_label']
    needed2=temp2.loc[:,'fraud_label']
    FDR1=sum(needed1)/numbads
    FDR2=sum(needed2)/numbads
    FDRate=np.maximum(FDR1,FDR2)
# print j, column, FDR1, FDR2, FDRate
    KS.loc[j,"FDR"]=FDRate
    j = j+1

CPU times: user 3min 22s, sys: 1min 38s, total: 5min 1s
Wall time: 4min 27s

In [15]:
KS.sort_values(by=['ks'],ascending=False,inplace=True)
KS

                             field        ks       FDR
0                      fraud_label  1.000000  1.000000
89                Days_fulladdress  0.328941  0.354127
9             fulladdress_30_count  0.327827  0.351045
8             fulladdress_14_count  0.317954  0.341218
7              fulladdress_7_count  0.298436  0.319813
6              fulladdress_3_count  0.276319  0.297493
5              fulladdress_1_count  0.246519  0.267844
88                        Days_ssn  0.224871  0.251353
27                    ssn_30_count  0.224655  0.251437
96      Days_fulladdress_homephone  0.224513  0.249688
98              Days_firstname_ssn  0.224081  0.250604
99               Days_lastname_ssn  0.223893  0.250437
69           firstnamessn_30_count  0.223776  0.250604
75            lastnamessn_30_count  0.223692  0.250437
57   fulladdresshomephone_30_count  0.223523  0.250187
90                    Days_namedob  0.223434  0.249938
93                Days_ssn_namedob  0.223329  0.249521
21                namedob_30_count  0.223080  0.249771
45             ssnnamedob_30_count  0.222973  0.249771
56   fulladdresshomephone_14_count  0.213874  0.241109
26                    ssn_14_count  0.212569  0.241526
68           firstnamessn_14_count  0.211992  0.239277
20                namedob_14_count  0.211867  0.237611
74            lastnamessn_14_count  0.211586  0.238861
44             ssnnamedob_14_count  0.211206  0.237195
55    fulladdresshomephone_7_count  0.195531  0.223869
12               homephone_3_count  0.193148  0.203964
19                 namedob_7_count  0.192239  0.217956
25                     ssn_7_count  0.191997  0.221787
13               homephone_7_count  0.191799  0.205214
..                             ...       ...       ...
37            ssnhomephone_7_count  0.028493  0.064213
61        namedobhomephone_7_count  0.028461  0.064129
31          ssnfulladdress_7_count  0.028047  0.063463
106                  Day_of _Month  0.018475  0.027984
78    firstnamefulladdress_3_count  0.018215  0.055218
84     lastnamefulladdress_3_count  0.015857  0.053219
48      fulladdressnamedob_3_count  0.014836  0.052386
30          ssnfulladdress_3_count  0.014434  0.052053
60        namedobhomephone_3_count  0.014422  0.051970
36            ssnhomephone_3_count  0.014322  0.051970
1                          nameDOB  0.014123  0.034730
3                          namedob  0.014123  0.034730
103                        new_zip  0.013523  0.029316
2                      fulladdress  0.013260  0.033231
104                           zip3  0.013245  0.029400
105                  Month_of_Year  0.012434  0.029150
107                         RANDOM  0.011004  0.029483
102                    Day_of_Week  0.009984  0.029566
77    firstnamefulladdress_1_count  0.008507  0.046973
83     lastnamefulladdress_1_count  0.006331  0.045224
47      fulladdressnamedob_1_count  0.005444  0.044307
59        namedobhomephone_1_count  0.005433  0.044557
35            ssnhomephone_1_count  0.005427  0.044557
29          ssnfulladdress_1_count  0.005364  0.044224
76    firstnamefulladdress_0_count  0.003257  0.043058
82     lastnamefulladdress_0_count  0.002086  0.041976
46      fulladdressnamedob_0_count  0.001761  0.041642
34            ssnhomephone_0_count  0.001703  0.041559
58        namedobhomephone_0_count  0.001699  0.041559
28          ssnfulladdress_0_count  0.001685  0.041559

[108 rows x 3 columns]

In [16]:
KS.sort_values(by=['FDR'],ascending=False,inplace=True)
KS

                             field        ks       FDR
0                      fraud_label  1.000000  1.000000
89                Days_fulladdress  0.328941  0.354127
9             fulladdress_30_count  0.327827  0.351045
8             fulladdress_14_count  0.317954  0.341218
7              fulladdress_7_count  0.298436  0.319813
6              fulladdress_3_count  0.276319  0.297493
5              fulladdress_1_count  0.246519  0.267844
27                    ssn_30_count  0.224655  0.251437
88                        Days_ssn  0.224871  0.251353
98              Days_firstname_ssn  0.224081  0.250604
69           firstnamessn_30_count  0.223776  0.250604
75            lastnamessn_30_count  0.223692  0.250437
99               Days_lastname_ssn  0.223893  0.250437
57   fulladdresshomephone_30_count  0.223523  0.250187
90                    Days_namedob  0.223434  0.249938
21                namedob_30_count  0.223080  0.249771
45             ssnnamedob_30_count  0.222973  0.249771
96      Days_fulladdress_homephone  0.224513  0.249688
93                Days_ssn_namedob  0.223329  0.249521
26                    ssn_14_count  0.212569  0.241526
56   fulladdresshomephone_14_count  0.213874  0.241109
68           firstnamessn_14_count  0.211992  0.239277
74            lastnamessn_14_count  0.211586  0.238861
20                namedob_14_count  0.211867  0.237611
44             ssnnamedob_14_count  0.211206  0.237195
55    fulladdresshomephone_7_count  0.195531  0.223869
25                     ssn_7_count  0.191997  0.221787
67            firstnamessn_7_count  0.191655  0.221621
43              ssnnamedob_7_count  0.191264  0.221621
73             lastnamessn_7_count  0.191584  0.220788
..                             ...       ...       ...
37            ssnhomephone_7_count  0.028493  0.064213
61        namedobhomephone_7_count  0.028461  0.064129
31          ssnfulladdress_7_count  0.028047  0.063463
78    firstnamefulladdress_3_count  0.018215  0.055218
84     lastnamefulladdress_3_count  0.015857  0.053219
48      fulladdressnamedob_3_count  0.014836  0.052386
30          ssnfulladdress_3_count  0.014434  0.052053
60        namedobhomephone_3_count  0.014422  0.051970
36            ssnhomephone_3_count  0.014322  0.051970
77    firstnamefulladdress_1_count  0.008507  0.046973
83     lastnamefulladdress_1_count  0.006331  0.045224
35            ssnhomephone_1_count  0.005427  0.044557
59        namedobhomephone_1_count  0.005433  0.044557
47      fulladdressnamedob_1_count  0.005444  0.044307
29          ssnfulladdress_1_count  0.005364  0.044224
76    firstnamefulladdress_0_count  0.003257  0.043058
82     lastnamefulladdress_0_count  0.002086  0.041976
46      fulladdressnamedob_0_count  0.001761  0.041642
28          ssnfulladdress_0_count  0.001685  0.041559
58        namedobhomephone_0_count  0.001699  0.041559
34            ssnhomephone_0_count  0.001703  0.041559
3                          namedob  0.014123  0.034730
1                          nameDOB  0.014123  0.034730
2                      fulladdress  0.013260  0.033231
102                    Day_of_Week  0.009984  0.029566
107                         RANDOM  0.011004  0.029483
104                           zip3  0.013245  0.029400
103                        new_zip  0.013523  0.029316
105                  Month_of_Year  0.012434  0.029150
106                  Day_of _Month  0.018475  0.027984

[108 rows x 3 columns]

In [17]:
KS['rank_ks']=KS['ks'].rank(ascending=True)
KS['rank_FDR']=KS['FDR'].rank(ascending=True)
KS.head(10)

                   field        ks       FDR  rank_ks  rank_FDR
0            fraud_label  1.000000  1.000000    108.0     108.0
89      Days_fulladdress  0.328941  0.354127    107.0     107.0
9   fulladdress_30_count  0.327827  0.351045    106.0     106.0
8   fulladdress_14_count  0.317954  0.341218    105.0     105.0
7    fulladdress_7_count  0.298436  0.319813    104.0     104.0
6    fulladdress_3_count  0.276319  0.297493    103.0     103.0
5    fulladdress_1_count  0.246519  0.267844    102.0     102.0
27          ssn_30_count  0.224655  0.251437    100.0     101.0
88              Days_ssn  0.224871  0.251353    101.0     100.0
98    Days_firstname_ssn  0.224081  0.250604     98.0      98.5

In [18]:
KS['average_rank']=(KS['rank_ks']+KS['rank_FDR'])/2
KS.sort_values(by=['average_rank'],ascending=False,inplace=True)
KS.head(10)

                   field        ks       FDR  rank_ks  rank_FDR  average_rank
0            fraud_label  1.000000  1.000000    108.0     108.0        108.00
89      Days_fulladdress  0.328941  0.354127    107.0     107.0        107.00
9   fulladdress_30_count  0.327827  0.351045    106.0     106.0        106.00
8   fulladdress_14_count  0.317954  0.341218    105.0     105.0        105.00
7    fulladdress_7_count  0.298436  0.319813    104.0     104.0        104.00
6    fulladdress_3_count  0.276319  0.297493    103.0     103.0        103.00
5    fulladdress_1_count  0.246519  0.267844    102.0     102.0        102.00
27          ssn_30_count  0.224655  0.251437    100.0     101.0        100.50
88              Days_ssn  0.224871  0.251353    101.0     100.0        100.50
98    Days_firstname_ssn  0.224081  0.250604     98.0      98.5         98.25

In [19]:
KS.tail(10)

,field,ks,FDR,rank_ks,rank_FDR,average_rank
103,new_zip,0.013523,0.029316,18.0,3.0,10.5
104,zip3,0.013245,0.029400,16.0,4.0,10.0
82,lastnamefulladdress_0_count,0.002086,0.041976,5.0,14.0,9.5
102,Day_of_Week,0.009984,0.029566,13.0,6.0,9.5
107,RANDOM,0.011004,0.029483,14.0,5.0,9.5
105,Month_of_Year,0.012434,0.029150,15.0,2.0,8.5
46,fulladdressnamedob_0_count,0.001761,0.041642,4.0,13.0,8.5
34,ssnhomephone_0_count,0.001703,0.041559,3.0,11.0,7.0
58,namedobhomephone_0_count,0.001699,0.041559,2.0,11.0,6.5
28,ssnfulladdress_0_count,0.001685,0.041559,1.0,11.0,6.0

In [20]:
## export to csv
KS.to_csv("KS_FDR_AllVariables.csv",index=False)